spring:
  data:
    mongodb:
      username: ctalantimur
      password: Bawer.123
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
